- name: Install Adobe Reader
  hosts: windows
  tasks:
  
    - name: Create a Folder
      win_file:
        path: "c:\\installs"
        state: "directory"
        creates: "c:\\installs"

    - name: Copy Files
      - win_copy:
          src: "/srv/Adobe"
          dest: "c:\\installs"
          creates: "c:\\installs\\Adobe"

    - name: install Adobe
      ansible.windows.win_package:
        path: "c:\\installs\\setup.exe"
        state: "present"
