- name: Install 7-Zip on Windows
  hosts: windows
  tasks:
  
    - name: Create a Folder
      win_file:
        path: "c:\\installs"
        state: "directory"
        creates: "c:\\installs"

    - name: Copy Installler
      win_copy:
        src: "/srv/7z.exe"
        dest: "c:\\installs"
        creates: "c:\\installs\\7z.exe"

    - name: install 7zip
      become: true
      become_user: root
      ansible.windows.win_package:
        path: "c:\\installs\\7z.exe"
        state: "present"
