- name: Install 7-Zip on Windows
  hosts: windows
  tasks:
  
    - name: Create a Folder
      win_file:
        path: "c:\\installs"
        state: "directory"
        creates: "c:\\installs"

    - name: Copy Installler
      win_copy:
        src: "/srv/7z.msi"
        dest: "c:\\installs"
        creates: "c:\\installs\\7z.msi"

    - name: install 7zip
      win_package:
        path: "c:\\installs\\7z.msi"
        arguments: /silent
        state: "present"
