windows: 
  hosts: 
      10.71.31.66:
      vars:
        ansible_connection: winrm
        ansible_port: 5985
        ansible_winrm_server_cert_validation: ignore
        ansible_user: semaphoreClient
        ansible_password: 1!demo
        ansible_winrm_transport: ntlm
